<a href="https://colab.research.google.com/github/mdaugherity/Python-Tutorials/blob/master/Python_Boot_Camp_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Boot Camp Lesson 2
Thermo Fall 2020  

Dr. Daugherity

**Intro to numpy**


In [1]:
import numpy as np
np.__version__

'1.18.5'

# Creating Arrays
In normal python we do **NOT** declare our variables before using them.

In numpy, you **MUST** declare arrays before using them!!!!!!!!!


In [3]:
x = np.array([1,2,17])
print(x)

[ 1  2 17]


In [4]:
np.array( [(1,2,3), (4,5,6) ] )

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros( (2,3))  # create array with 2 rows, 3 cols

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [9]:
np.arange(0, 10, 2)  # arange is JUST like range with for loops

array([0, 2, 4, 6, 8])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 17)

array([0.    , 0.0625, 0.125 , 0.1875, 0.25  , 0.3125, 0.375 , 0.4375,
       0.5   , 0.5625, 0.625 , 0.6875, 0.75  , 0.8125, 0.875 , 0.9375,
       1.    ])

# INDEXING ARRAYS


In [13]:
x = np.linspace(0,8,9)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [15]:
x[1]

1.0

In [16]:
x.shape  # tells you how many elements in rows and cols

(9,)

In [20]:
x.size  # number of elements in x

9

In [21]:
x[0:5]  # elements between 0 and 4

array([0., 1., 2., 3., 4.])

In [22]:
x[:5]

array([0., 1., 2., 3., 4.])

In [23]:
x[6:]  # 6th element to the end

array([6., 7., 8.])

In [25]:
x[-1]  # the last element

8.0

In [27]:
y = np.array( [(1,2,3), (4,5,6)])
print(y)

[[1 2 3]
 [4 5 6]]


In [30]:
y[0, 2]  # row 0, col 2

3

In [31]:
y[:, 1]  # all rows in col 1

array([2, 5])

In [36]:
y[1:,2]   

array([6])

# LOOPING OVER ARRAYS!


In [39]:
# you often DONT have to loop, you can operate on the entire array
x = np.linspace(0,10,50)
np.sin(x)

array([ 0.        ,  0.20266794,  0.39692415,  0.57470604,  0.72863478,
        0.85232157,  0.94063279,  0.98990308,  0.99808748,  0.96484631,
        0.89155923,  0.78126802,  0.63855032,  0.46932961,  0.2806294 ,
        0.08028167, -0.12339814, -0.32195632, -0.50715171, -0.67129779,
       -0.80758169, -0.91034694, -0.97532829, -0.99982867, -0.9828312 ,
       -0.92504137, -0.82885774, -0.6982724 , -0.53870529, -0.35677924,
       -0.16004509,  0.04333173,  0.24491007,  0.43632343,  0.6096272 ,
        0.75762842,  0.8741843 ,  0.9544572 ,  0.99511539,  0.99447137,
        0.95255185,  0.8710967 ,  0.75348673,  0.60460332,  0.43062587,
        0.23877532,  0.0370144 , -0.16628279, -0.36267843, -0.54402111])

In [40]:
x = np.linspace(0,10,3)
for val in x:
  print(val)

0.0
5.0
10.0


In [42]:
# pretty gross
for i in range(len(x)):
  print(x[i])

0.0
5.0
10.0


In [44]:
for i,val in enumerate(x):
  print(f"index {i}, value {val}")

index 0, value 0.0
index 1, value 5.0
index 2, value 10.0
